  db_version: {{ nextcloud.db_version | default("17-alpine") }}
  use_mariadb: {{ nextcloud.use_mariadb | default(False) }}
  redis_version: {{ nextcloud.redis_version | default("5.0-alpine") }}
  oidc_enabled: {{ nextcloud.oidc_enabled | default(False) }}
  oidc_client_id: {{ nextcloud.oidc_client_id | default(False) }}
  oidc_client_secret: {{ nextcloud.oidc_client_secret | default(False) }}
  oidc_discovery_uri: {{ nextcloud.oidc_discovery_uri | default(False) }}
  oidc_scope: {{ nextcloud.oidc_scope | default("openid email profile") }}
  oidc_uid_mapping: {{ nextcloud.oidc_uid_mapping | default("preferred_username") }}
  talk_enabled: {{ nextcloud.talk_enabled | default(False) }}
  talk_turn_version: {{ nextcloud.talk_turn_version | default("4.6.2-r1") }}
  talk_turn_port: {{ nextcloud.talk_turn_port | default(3478) }}
  talk_turn_schemes: {{ nextcloud.talk_turn_schemes | default("turn") }}
  talk_turn_protocols: {{ nextcloud.talk_turn_protocols | default("udp,tcp") }}
  talk_turn_relay_min: {{ nextcloud.talk_turn_relay_min | default(49160) }}
  talk_turn_relay_max: {{ nextcloud.talk_turn_relay_max | default(49200) }}
  talk_turn_external_ip: {{ nextcloud.talk_turn_external_ip | default(False) }}
  talk_signaling_enabled: {{ nextcloud.talk_signaling_enabled | default(False) }}
  talk_signaling_subdomain: {{ nextcloud.talk_signaling_subdomain | default("signaling") }}
  talk_signaling_version: {{ nextcloud.talk_signaling_version | default("79d6093") }}
  talk_signaling_port: {{ nextcloud.talk_signaling_port | default(8080) }}
  talk_signaling_verify: {{ nextcloud.talk_signaling_verify | default(True) }}
  talk_recording_enabled: {{ nextcloud.talk_recording_enabled | default(False) }}
  talk_recording_version: {{ nextcloud.talk_recording_version | default("20260817_082005") }}
  talk_recording_subdomain: {{ nextcloud.talk_recording_subdomain | default("recording") }}
  talk_recording_consent: {{ nextcloud.talk_recording_consent | default(False) }}
