---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make adguard directories
  file:
    path: "{{ volumes_root }}/adguardhome/{{item}}"
    state: directory
  loop:
    - "work"
    - "config"

- name: Install bCrypt
  command: >
    pip install bcrypt

- name: Generate bCrypt password hash
  command: >
    python -c 'from passlib.hash import bcrypt; print(bcrypt.hash("{{default_password}}"))'
  register: passwrd

- name: Copy adguardhome config file into place.
  template:
    src: AdGuardHome.j2
    dest: "{{ volumes_root }}/adguardhome/config/AdGuardHome.yaml"
  vars:
    password: "{{passwrd.stdout}}"

- name: Reconfigure Systemd-resolved
  include_role:
    name: homelabos_systemd-resolve

- name: Start {{service_item}}
  include: includes/start.yml
