---
- name: Ensure /etc/systemd/resolved.conf.d exists
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copy homelabos.conf systemd resolve configuration into place.
  template:
    src: homelabos.conf
    dest: "/etc/systemd/resolved.conf.d/homelabos.conf"

- name: Check whether resolv.conf backup exists
  stat:
    path: /etc/resolv.conf.bkup
  register: resolv_conf_backup

- name: Check current resolv.conf path
  stat:
    path: /etc/resolv.conf
    follow: false
  register: resolv_conf_path

- name: Rename standard resolv.conf file
  command: mv /etc/resolv.conf /etc/resolv.conf.bkup
  when:
    - not resolv_conf_backup.stat.exists
    - not resolv_conf_path.stat.islnk | default(false)

- name: link the systemd resolve file into /etc
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Reload & Restart systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: "yes"
    daemon-reload: "yes"
    state: restarted
