###
##  Docker container to install HomelabOS from a container
##  Build the container like this:
##    docker build -f Dockerfile.dev . -t homelabos_installer:latest
##
##  Run the container like this:
##    touch $HOME/.homelabos_vault_pass
##    Make sure you have SSH keys generated!
##    docker run --name homelab_installer -it -e BRANCH=dev -v $HOME/.ssh/id_rsa:/root/.ssh/id_rsa -v $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub -v $HOME/.homelabos_vault_pass:/root/.homelabos_vault_pass homelabos_installer:latest
##
##  Inside the container run:
##    /entrypoint.sh
##
##  Until branch is merged:
##    docker run --name homelab_installer -it -e BRANCH=220_add_remote_deploy_of_hlos_ansible_api -v $HOME/.ssh/id_rsa:/root/.ssh/id_rsa -v $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub -v $HOME/.homelabos_vault_pass:/root/.homelabos_vault_pass homelabos_installer:latest
##################
FROM ubuntu:focal

RUN apt update && \
    apt install -qy sshpass python3 python3-pip git wget && \
    pip3 install ansible docker-py mitogen

ENV BRANCH=220_add_remote_deploy_of_hlos_ansible_api

RUN git clone https://gitlab.com/NickBusey/HomelabOS.git /install
RUN echo "#!/usr/bin/bash" > /entrypoint.sh && \
    echo "git checkout ${BRANCH}" >> /entrypoint.sh && \
    echo "./setup_hlos.sh" >> /entrypoint.sh && \
    chmod +x /entrypoint.sh

# Temporary local development of installer script:
RUN mkdir -p /install/bootstrap_install_local
COPY setup_hlos.sh /install/bootstrap_install_local/
RUN chmod +x /install/bootstrap_install_local/setup_hlos.sh

WORKDIR /install/bootstrap_install_local
ENTRYPOINT [ "/usr/bin/bash" ]
#ENTRYPOINT [ "/entrypoint.sh" ]
