---

- name: Setup {{service_item}}
  include_tasks: includes/setup.yml

- name: Configure telegraf
  template:
    src: "{{ playbook_dir }}/roles/tick/templates/telegraf.conf.j2"
    dest: "{{ volumes_root }}/tick/telegraf.conf"

- name: Start {{service_item}}
  include_tasks: includes/start.yml
