---

- name: Setup {{service_item}}
  include_tasks: includes/setup.yml

- name: Make Hermes data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: u+rwx,g+rwx,o+rx
  loop:
    - "{{ volumes_root }}/hermes/hermes-home"
    - "{{ volumes_root }}/hermes/workspace"

- name: Start {{service_item}}
  include_tasks: includes/start.yml
